### ISSUE TITLE
Badger panics when killing daemon

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/venus#2052]
**Describe the bug**
Killed the daemon with ctrl+c, got a panic

```
badger 2019/02/20 16:05:54 INFO: Storing value log head: {Fid:0 Len:46 Offset:144782451}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9b9191]

goroutine 3292 [running]:
gx/ipfs/QmU4emVTYFKnoJ5yK3pPEN9joyEx6U7y892PDx26ZtNxQd/badger/skl.(*Skiplist).IncrRef(...)
        /home/why/gopkg/src/gx/ipfs/QmU4emVTYFKnoJ5yK3pPEN9joyEx6U7y892PDx26ZtNxQd/badger/skl/skl.go:86
gx/ipfs/QmU4emVTYFKnoJ5yK3pPEN9joyEx6U7y892PDx26ZtNxQd/badger.(*DB).getMemTables(0xc00023e000, 0x0, 0x0, 0x0, 0x0)
        /home/why/gopkg/src/gx/ipfs/QmU4emVTYFKnoJ5yK3pPEN9joyEx6U7y892PDx26ZtNxQd/badger/db.go:444 +0xd1
gx/ipfs/QmU4emVTYFKnoJ5yK3pPEN9joyEx6U7y892PDx26ZtNxQd/badger.(*DB).get(0xc00023e000, 0xc01a210690, 0x4d, 0x4d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/why/gopkg/src/gx/ipfs/QmU4emVTYFKnoJ5yK3pPEN9joyEx6U7y892PDx26ZtNxQd/badger/db.go:476 +0x81
gx/ipfs/QmU4emVTYFKnoJ5yK3pPEN9joyEx6U7y892PDx26ZtNxQd/badger.(*Txn).Get(0xc02c000380, 0xc01a210640, 0x45, 0x50, 0x45, 0x50, 0xc02883aaa0)
        /home/why/gopkg/src/gx/ipfs/QmU4emVTYFKnoJ5yK3pPEN9joyEx6U7y892PDx26ZtNxQd/badger/txn.go:459 +0x10a
gx/ipfs/QmTNJogwkhnbHeRmAXWtzvN2KgVko2oNmHHQN1ggHVhF91/go-ds-badger.(*txn).Get(0xc02a1b9b70, 0xc01a2105f0, 0x45, 0xc02a1b9b70, 0xc02883ab00, 0x8a85ed, 0xc01aa67bc0, 0x3e)
        /home/why/gopkg/src/gx/ipfs/QmTNJogwkhnbHeRmAXWtzvN2KgVko2oNmHHQN1ggHVhF91/go-ds-badger/datastore.go:236 +0x74
gx/ipfs/QmTNJogwkhnbHeRmAXWtzvN2KgVko2oNmHHQN1ggHVhF91/go-ds-badger.(*Datastore).Get(0xc0000bd120, 0xc01a2105f0, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/why/gopkg/src/gx/ipfs/QmTNJogwkhnbHeRmAXWtzvN2KgVko2oNmHHQN1ggHVhF91/go-ds-badger/datastore.go:142 +0xac
gx/ipfs/QmUadX5EcvrBmxAV9sE7wUWtWSqxns5K84qKJBixmcT1w9/go-datastore/keytransform.(*ktds).Get(0xc0001f2c60, 0xc01aa67bc0, 0x3e, 0x30, 0x63647c, 0xea0000000049ea42, 0xc02883ac30, 0x4a1e3f)
        /home/why/gopkg/src/gx/ipfs/QmUadX5EcvrBmxAV9sE7wUWtWSqxns5K84qKJBixmcT1w9/go-datastore/keytransform/keytransform.go:40 +0x76
gx/ipfs/QmRu7tiRnFk9mMPpVECQTBQJqXtmG132jJxA1w9A7TtpBz/go-ipfs-blockstore.(*blockstore).Get(0xc0001f2c80, 0xc027165170, 0x26, 0x26, 0x1f073c0, 0x94b700, 0x1445040)
        /home/why/gopkg/src/gx/ipfs/QmRu7tiRnFk9mMPpVECQTBQJqXtmG132jJxA1w9A7TtpBz/go-ipfs-blockstore/blockstore.go:123 +0x83
github.com/filecoin-project/go-filecoin/vm.Storage.Get(0xc02bb50030, 0xc02bb50240, 0x1448720, 0xc0001f2c80, 0xc027165170, 0x26, 0xc02bb50240, 0x1448720, 0xc0001f2c80, 0xc027165170, ...)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/vm/storage.go:135 +0x97
github.com/filecoin-project/go-filecoin/vm.(*Context).ReadStorage(0xc024920070, 0xc01f964000, 0x1449f00, 0x7f2e16798e88, 0x0, 0xc)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/vm/context.go:82 +0x72
github.com/filecoin-project/go-filecoin/actor.WithState(0x1449f00, 0xc024920070, 0x10a0ea0, 0xc02589f9a0, 0xc02883aeb8, 0x119e0a0, 0x11dcd20, 0xc024920070, 0xc02c4288c8)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/actor/storage.go:41 +0x3e
github.com/filecoin-project/go-filecoin/actor/builtin/storagemarket.(*Actor).GetTotalStorage(0x1f06188, 0x1449f00, 0xc024920070, 0x0, 0x0, 0x0, 0x0)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/actor/builtin/storagemarket/storagemarket.go:206 +0x18d
reflect.Value.call(0xc027d88f80, 0xc00000ed28, 0x13, 0x12359f1, 0x4, 0xc02883b448, 0x2, 0x2, 0x113e001, 0xc023eaea50, ...)
        /home/why/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0xc027d88f80, 0xc00000ed28, 0x13, 0xc02883b448, 0x2, 0x2, 0x0, 0x0, 0x0)
        /home/why/go/src/reflect/value.go:308 +0xa4
github.com/filecoin-project/go-filecoin/actor.MakeTypedExport.func2(0x1449f00, 0xc024920070, 0x123fbc9, 0xf, 0xc023eaea50, 0x1, 0x0, 0xc024920070)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/actor/export.go:94 +0x49b
github.com/filecoin-project/go-filecoin/vm.send(0x1444280, 0xc0000c8010, 0x1399f28, 0xc024920070, 0xc024920070, 0xc02883b5e8, 0x94b4c9, 0x11fe3a0, 0xc024920070, 0xc02589f940)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/vm/vm.go:55 +0x137
github.com/filecoin-project/go-filecoin/vm.Send(0x1444280, 0xc0000c8010, 0xc024920070, 0xc02589f920, 0x143dc80, 0xc02589f760, 0xc018f50dc0, 0x0, 0x0)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/vm/vm.go:22 +0x4f
github.com/filecoin-project/go-filecoin/consensus.CallQueryMethod(0x1444280, 0xc0000c8010, 0x1446a40, 0xc01ad556c0, 0x143dc80, 0xc02589f760, 0x1056300476ea0000, 0x41e437ce463a8d59, 0xaeb57a1d265de7d9, 0x123fbc9, ...)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/consensus/processor.go:371 +0x29c
github.com/filecoin-project/go-filecoin/consensus.(*MarketView).Total(0x1f06188, 0x1444280, 0xc0000c8010, 0x1446a40, 0xc01ad556c0, 0x1448720, 0xc0001f2c80, 0x180, 0x180, 0x9028651f00000000)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/consensus/power_table_view.go:44 +0x156
github.com/filecoin-project/go-filecoin/consensus.IsWinningTicket(0x1444280, 0xc0000c8010, 0x1448720, 0xc0001f2c80, 0x1441400, 0x1f06188, 0x1446a40, 0xc01ad556c0, 0xc019324160, 0x20, ...)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/consensus/expected.go:321 +0x89
github.com/filecoin-project/go-filecoin/consensus.(*Expected).validateMining(0xc00033c000, 0x1444280, 0xc0000c8010, 0x1446a40, 0xc01ad556c0, 0xc01b1a79b0, 0xc01b49ade0, 0x8ca6c0, 0xc028d2fb60)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/consensus/expected.go:303 +0x37e
github.com/filecoin-project/go-filecoin/consensus.(*Expected).RunStateTransition(0xc00033c000, 0x1444280, 0xc0000c8010, 0xc01b1a79b0, 0xc0289e8000, 0xe0a, 0x1000, 0x1446a40, 0xc01ad556c0, 0xe0a, ...)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/consensus/expected.go:235 +0xa5
github.com/filecoin-project/go-filecoin/chain.(*DefaultSyncer).syncOne(0xc0001f4ac0, 0x1444280, 0xc0000c8010, 0xc01b1ec2d0, 0xc01b1a79b0, 0x0, 0x0)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/chain/default_syncer.go:217 +0x1e8
github.com/filecoin-project/go-filecoin/chain.(*DefaultSyncer).HandleNewBlocks(0xc0001f4ac0, 0x1444280, 0xc0000c8010, 0xc01f05eb70, 0x1, 0x1, 0x0, 0x0)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/chain/default_syncer.go:363 +0x1d4
github.com/filecoin-project/go-filecoin/node.(*Node).Start.func1(0xc00003c4b0, 0x22, 0xc01f05eb70, 0x1, 0x1, 0x3989)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/node/node.go:486 +0x73
github.com/filecoin-project/go-filecoin/protocol/hello.(*Handler).processHelloMessage(0xc01f6aa180, 0xc00003c4b0, 0x22, 0xc01efc9bf0, 0x0, 0x1000)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/protocol/hello/hello.go:104 +0x85
github.com/filecoin-project/go-filecoin/protocol/hello.(*Handler).handleNewStream(0xc01f6aa180, 0x144a780, 0xc01f0606a0)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/protocol/hello/hello.go:85 +0x2c7
github.com/filecoin-project/go-filecoin/protocol/hello.(*Handler).handleNewStream-fm(0x144a780, 0xc01f0606a0)
        /home/why/gopkg/src/github.com/filecoin-project/go-filecoin/protocol/hello/hello.go:66 +0x3e
gx/ipfs/QmcNGX5RaxPPCYwa6yGXM1EcUbrreTTinixLcYGmMwf1sx/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc01efc6aa0, 0x10, 0x7f2d541121a8, 0xc01f0606a0, 0x19978, 0xc01f6a8860)
        /home/why/gopkg/src/gx/ipfs/QmcNGX5RaxPPCYwa6yGXM1EcUbrreTTinixLcYGmMwf1sx/go-libp2p/p2p/host/basic/basic_host.go:299 +0x9d
created by gx/ipfs/QmcNGX5RaxPPCYwa6yGXM1EcUbrreTTinixLcYGmMwf1sx/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
        /home/why/gopkg/src/gx/ipfs/QmcNGX5RaxPPCYwa6yGXM1EcUbrreTTinixLcYGmMwf1sx/go-libp2p/p2p/host/basic/basic_host.go:257 +0x6cb
```

**Comment by rosalinekarr** [comment]
@whyrusleeping, any chance you can provide more logs so we can figure out where the code that doesn't exit cleanly is?

**Comment by whyrusleeping** [comment]
@rosalinekarr those logs are very sufficient. we're processing a new block (you can see the call to `HandleNewBlocks`) after our datastore has been closed, which incurs a datastore read. Since we pressed ctrl+c, other parts of filecoin have started to shut down, including the datastore. Reads on a closed badgerDB instance will panic (as seen in the top of the stack trace)

**Comment by schomatis** [comment]
Seems similar to https://github.com/ipfs/go-ipfs/issues/4820, but I'm not sure how much does the gfc shutdown functionality diverges from `go-ipfs`.

**Comment by whyrusleeping** [comment]
@schomatis yeah, its probably very similar to go-ipfs here. One solution could be to defer closing the repo until everything else has exited

**Comment by Stebalien** [comment]
https://github.com/ipfs/go-ds-badger/pull/53
