### ISSUE TITLE
null pointer exeption

### ISSUE THREAD

**Issue by zl03jsj** [filecoin-project/venus#4578]
```
2021-10-29T17:36:51.068+0800    ERROR   /fil/hello      discovery/hello_protocol.go:170 fail to save block to tipset
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x10c873f]

goroutine 12879 [running]:
github.com/dgraph-io/badger/v2/skl.(*Skiplist).IncrRef(...)
        /root/workspacego/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/skl/skl.go:86
github.com/dgraph-io/badger/v2.(*DB).getMemTables(0xc000a87c00, 0x0, 0x0, 0x0, 0x0)
        /root/workspacego/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/db.go:629 +0xdf
github.com/dgraph-io/badger/v2.(*DB).get(0xc000a87c00, 0xc07a3a4050, 0x4a, 0x4a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/workspacego/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/db.go:664 +0x92
github.com/dgraph-io/badger/v2.(*Txn).Get(0xc07a20e900, 0xc07a3a4000, 0x42, 0x50, 0x42, 0x50, 0xc0073af8f0)
        /root/workspacego/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/txn.go:471 +0x10b
github.com/filecoin-project/venus/pkg/util/blockstoreutil.(*BadgerBlockstore).View.func1(0xc07a20e900, 0x0, 0xc07a20e900)
        /root/hj/venus/pkg/util/blockstoreutil/badger.go:187 +0x75
github.com/dgraph-io/badger/v2.(*DB).View(0xc000a87c00, 0xc0073af968, 0x0, 0x0)
        /root/workspacego/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/txn.go:802 +0x95
github.com/filecoin-project/venus/pkg/util/blockstoreutil.(*BadgerBlockstore).View(0xc007a1da70, 0xc07a1b1dd0, 0x26, 0xc079d35c00, 0x7f6474bfdac8, 0xa0)
        /root/hj/venus/pkg/util/blockstoreutil/badger.go:186 +0xc5
github.com/ipfs/go-ipld-cbor.(*BasicIpldStore).Get(0xc07a209bc0, 0x32b03e0, 0xc074da88a0, 0xc07a1b1dd0, 0x26, 0x2cd2400, 0xc07a2040a0, 0x203001, 0xc07a2040a0)
        /root/workspacego/pkg/mod/github.com/ipfs/go-ipld-cbor@v0.0.5/store.go:58 +0xb9
github.com/filecoin-project/go-amt-ipld/v2.LoadAMT(0x32b03e0, 0xc074da88a0, 0x7f64b4263100, 0xc079d35be0, 0xc07a1b1dd0, 0x26, 0xc000100000, 0x0, 0xc0073afb30)
        /root/workspacego/pkg/mod/github.com/filecoin-project/go-amt-ipld/v2@v2.1.1-0.20201006184820-924ee87a1349/amt.go:56 +0x9a
github.com/filecoin-project/specs-actors/actors/util/adt.AsArray(0x32a35a8, 0xc079d35be0, 0xc07a1b1dd0, 0x26, 0xc007a1da70, 0xc0073afb01, 0x56cc6c)
        /root/workspacego/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.14/actors/util/adt/array.go:22 +0xbf
github.com/filecoin-project/venus/pkg/chain.(*MessageStore).loadAMTCids(0xc000ea9578, 0x32b03e0, 0xc074da88a0, 0xc07a1b1dd0, 0x26, 0x7, 0x7, 0x0, 0x0, 0x0)
        /root/hj/venus/pkg/chain/message_store.go:355 +0x18c
github.com/filecoin-project/venus/pkg/chain.(*MessageStore).LoadMetaMessages(0xc000ea9578, 0x32b03e0, 0xc074da88a0, 0xc075b840f0, 0x26, 0xc0014b9a90, 0x0, 0x1, 0xc079e07000, 0xf3, ...)
        /root/hj/venus/pkg/chain/message_store.go:81 +0x199
github.com/filecoin-project/venus/pkg/discovery.(*HelloProtocolHandler).loadLocalFullTipset(0xc000190070, 0x32b03e0, 0xc074da88a0, 0xc05a927a40, 0x130, 0x20, 0x0, 0x0)
        /root/hj/venus/pkg/discovery/hello_protocol.go:196 +0x145
github.com/filecoin-project/venus/pkg/discovery.(*HelloProtocolHandler).handleNewStream(0xc000190070, 0x32d36f8, 0xc074d9da40)
        /root/hj/venus/pkg/discovery/hello_protocol.go:158 +0x485
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc074ddbf10, 0x10, 0x7f64a45fc2e8, 0xc074d9da40, 0x1, 0x0)
        /root/workspacego/pkg/mod/github.com/libp2p/go-libp2p@v0.14.2/p2p/host/basic/basic_host.go:574 +0xa2
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
        /root/workspacego/pkg/mod/github.com/libp2p/go-libp2p@v0.14.2/p2p/host/basic/basic_host.go:421 +0x63a
```

**Comment by Fatman13** [comment]
Closing old issues to have a fresh start.
