### ISSUE TITLE
TestDSBackendParallel panic

### ISSUE THREAD

**Issue by zl03jsj** [filecoin-project/venus#4619]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/venus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [venus forum](https://github.com/filecoin-project/venus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/venus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/venus/issues) and the [venus forum](https://github.com/filecoin-project/venus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`latest release`](https://github.com/filecoin-project/venus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to venus.

### Venus component

- [ ] venus daemon - chain sync
- [ ] venus auth - authentication
- [ ] venus gateway - chain service gateway
- [ ] venus miner - mining and block production
- [ ] venus sealer/worker - sealing
- [ ] venus sealer - proving(WindowPoSt)
- [ ] venus market - storage deal
- [ ] venus market - retrieval deal
- [ ] venus market - data transfer
- [ ] venus light-weight client
- [ ] venus JSON-RPC API
- [ ] venus messager - message management (mpool)
- [ ] Other

### Venus Version

```text
"Commit": "v1.1.3-rc1 fc255320bfb0140b9254db3d3db234ef349c53a8"
```

### Describe the Bug

TestDSBackendParallel failed and get a panic.
it doesn't happen every time, but you guys should find out why it occurs in this certain testing.

### Logging Information

```text
=== RUN   TestDSBackendParallel
panic: runtime error: index out of range [0] with length 0

goroutine 77 [running]:
github.com/awnumar/memguard/core.(*Coffer).View(0xc0000dc6c0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/awnumar/memguard@v0.22.2/core/coffer.go:112 +0x211
github.com/awnumar/memguard/core.Open(0xc000482018, 0xc, 0x64, 0x7f62dd1cad40)
	/go/pkg/mod/github.com/awnumar/memguard@v0.22.2/core/enclave.go:101 +0x65
github.com/awnumar/memguard.(*Enclave).Open(0xc00048e000, 0x76fe4e, 0x400, 0x7f62dd1cad40)
	/go/pkg/mod/github.com/awnumar/memguard@v0.22.2/enclave.go:43 +0x32
github.com/filecoin-project/venus/pkg/crypto.(*KeyInfo).UsePrivateKey(0xc000192000, 0xc0024aad68, 0x0, 0x0)
	/go/src/github.com/filecoin-project/venus/pkg/crypto/keyinfo.go:167 +0x47
github.com/filecoin-project/venus/pkg/crypto.(*KeyInfo).PublicKey(0xc000192000, 0x7f630e6691d8, 0x8, 0x52c57b, 0xc0001e80a0, 0xc0000a0c00)
	/go/src/github.com/filecoin-project/venus/pkg/crypto/keyinfo.go:157 +0x73
github.com/filecoin-project/venus/pkg/crypto.(*KeyInfo).Address(0xc000192000, 0x7f630e6691d8, 0x20, 0xc000488080, 0xc00048e000)
	/go/src/github.com/filecoin-project/venus/pkg/crypto/keyinfo.go:141 +0x2f
github.com/filecoin-project/venus/pkg/wallet.(*DSBackend).putKeyInfo(0xc0001121e0, 0xc000192000, 0xc00048e000, 0x1)
	/go/src/github.com/filecoin-project/venus/pkg/wallet/dsbackend.go:158 +0x50
github.com/filecoin-project/venus/pkg/wallet.(*DSBackend).newSecpAddress(0xc0001121e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/filecoin-project/venus/pkg/wallet/dsbackend.go:139 +0xcc
github.com/filecoin-project/venus/pkg/wallet.(*DSBackend).NewAddress(0xc0001121e0, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/filecoin-project/venus/pkg/wallet/dsbackend.go:127 +0x15c
github.com/filecoin-project/venus/pkg/wallet.TestDSBackendParallel.func2(0xc0001121e0, 0xc002443080, 0xc00032e2c0)
	/go/src/github.com/filecoin-project/venus/pkg/wallet/dsbackend_test.go:134 +0x34
created by github.com/filecoin-project/venus/pkg/wallet.TestDSBackendParallel
	/go/src/github.com/filecoin-project/venus/pkg/wallet/dsbackend_test.go:133 +0x1c7
FAIL	github.com/filecoin-project/venus/pkg/wallet	0.741s
```

**Comment by zl03jsj** [comment]
this problem was fixed in #4629
