### ISSUE TITLE
[venus-auth] 获取token的翻页功能无法获取数据

### ISSUE THREAD

**Issue by cloudxin** [filecoin-project/venus#5180]
### 链服务模块 / Chain Service Components

- [ ] venus
- [X] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
venus-auth -v
venus-auth version 1.6.0'+3aa966b'
```

### 描述 / Describe the Bug

使用**venus-auth token list --limit 100**命令，可以查询更多的token信息
<img width="589" alt="image" src="https://user-images.githubusercontent.com/43364105/183857316-e3e0200a-dd53-4b17-8a91-3448752781fd.png">

### 日志 / Logging Information

```text
2022/08/10 15:36:48 http: panic serving [::1]:50906: interface conversion: interface {} is nil, not string
goroutine 18485350 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0xf02bc0, 0xc00052f140})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/filecoin-project/venus-auth/auth.toTokenInfo(0xc0004b71f0)
        /opt/venus-auth/auth/jwt.go:183 +0x1d4
github.com/filecoin-project/venus-auth/auth.(*jwtOAuth).Tokens(0xc00026e200?, {0xef7440?, 0xc000011260?}, 0xa66bc5?, 0x3e8)
        /opt/venus-auth/auth/jwt.go:219 +0xbd
github.com/filecoin-project/venus-auth/auth.(*oauthApp).Tokens(0xc0002c83d0, 0x1040af9?)
        /opt/venus-auth/auth/app.go:168 +0xa3
github.com/gin-gonic/gin.(*Context).Next(...)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165
github.com/filecoin-project/venus-auth/auth.CorsMiddleWare.func1(0xc00026e200)
        /opt/venus-auth/auth/route.go:99 +0x138
github.com/gin-gonic/gin.(*Context).Next(...)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00034a820, 0xc00026e200)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:489 +0x63e
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00034a820, {0x11c1098?, 0xc00088a550}, 0xc0002f3800)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:445 +0x1c5
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc0002a3590, {0x11c0138, 0xc00029ad20}, 0xc000580000?)
```

**Comment by simlecode** [comment]
skip是跳过多少条数据，若要查第21条到第61条数据，skip要用20 limit要用40，panic是因为手动加了个其它地方生成的token到数据库里面
