### ISSUE TITLE
[venus-messager] 单元测试存在偶发性错误

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/venus#5211]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [X] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
commit: ca3fde9
branch: master
```

### 描述 / Describe the Bug

go test -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic ./...
shell: /usr/bin/bash -e {0}

### 日志 / Logging Information

```text
go test -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic ./...
  shell: /usr/bin/bash -e {0}

... ...

2022/08/22 07:23:57 /home/runner/work/venus-messager/venus-messager/models/mysql/address.go:96 record not found
[1.060ms] [rows:0] SELECT * FROM `addresses` WHERE `id` = 'd2e4c7dd-54db-41da-9167-5979381d8060' ORDER BY `addresses`.`id` LIMIT 1

2022/08/22 07:23:57 /home/runner/work/venus-messager/venus-messager/models/mysql/address.go:96 ExecQuery 'INSERT INTO `addresses` (`id`,`addr`,`nonce`,`weight`,`sel_msg_num`,`state`,`gas_over_estimation`,`max_fee`,`gas_fee_cap`,`gas_over_premium`,`is_deleted`,`created_at`,`updated_at`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)', arguments do not match: argument 5 expected [int64 - 0] does not match actual [int64 - 1]; call to Rollback transaction, was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
  - matches sql: 'INSERT INTO `addresses` \(`id`,`addr`,`nonce`,`weight`,`sel_msg_num`,`state`,`gas_over_estimation`,`max_fee`,`gas_fee_cap`,`gas_over_premium`,`is_deleted`,`created_at`,`updated_at`\) VALUES \(\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?\)'
  - is with arguments:
    0 - d2e4c7dd-54db-41da-9167-5979381d8060
    1 - t02457644170698675106
    2 - 986
    3 - 986
    4 - 986
    5 - unknow state 0
    6 - 986
    7 - +986
    8 - +986
    9 - 986
    10 - -1
    11 - {}
    12 - {}
  - should return Result having:
      LastInsertId: 1
      RowsAffected: 1
[1.733ms] [rows:0] INSERT INTO `addresses` (`id`,`addr`,`nonce`,`weight`,`sel_msg_num`,`state`,`gas_over_estimation`,`max_fee`,`gas_fee_cap`,`gas_over_premium`,`is_deleted`,`created_at`,`updated_at`) VALUES ('d2e4c7dd-54db-41da-9167-5979381d8060','t02457644170698675106',986,986,986,1,986.000000,'986','986',986.000000,-1,'2022-08-22 07:23:57.952','2022-08-22 07:23:57.981')

2022/08/22 07:23:57 /home/runner/work/venus-messager/venus-messager/models/mysql/address.go:101 call to Query 'SELECT * FROM `addresses` WHERE addr = ? and is_deleted = ? LIMIT 1' with args [{Name: Ordinal:1 Value:t2b3ptsj3zw3elh6jsjxrhw4axmlay5dt36perpmq} {Name: Ordinal:2 Value:-1}], was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
  - matches sql: 'INSERT INTO `addresses` \(`id`,`addr`,`nonce`,`weight`,`sel_msg_num`,`state`,`gas_over_estimation`,`max_fee`,`gas_fee_cap`,`gas_over_premium`,`is_deleted`,`created_at`,`updated_at`\) VALUES \(\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?\)'
  - is with arguments:
    0 - d2e4c7dd-54db-41da-9167-5979381d8060
    1 - t02457644170698675106
    2 - 986
    3 - 986
    4 - 986
    5 - unknow state 0
    6 - 986
    7 - +986
    8 - +986
    9 - 986
    10 - -1
    11 - {}
    12 - {}
  - should return Result having:
      LastInsertId: 1
      RowsAffected: 1
[0.287ms] [rows:0] SELECT * FROM `addresses` WHERE addr = 't2b3ptsj3zw3elh6jsjxrhw4axmlay5dt36perpmq' and is_deleted = -1 LIMIT 1
--- FAIL: TestAddress (0.04s)
    --- FAIL: TestAddress/mysql_test_save_address (0.03s)
        address_test.go:70: 
            	Error Trace:	address_test.go:70
            	            				testing.go:32
            	Error:      	Expected nil, but got: &fmt.wrapError{msg:"ExecQuery 'INSERT INTO `addresses` (`id`,`addr`,`nonce`,`weight`,`sel_msg_num`,`state`,`gas_over_estimation`,`max_fee`,`gas_fee_cap`,`gas_over_premium`,`is_deleted`,`created_at`,`updated_at`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)', arguments do not match: argument 5 expected [int64 - 0] does not match actual [int64 - 1]; call to Rollback transaction, was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:\n  - matches sql: 'INSERT INTO `addresses` \\(`id`,`addr`,`nonce`,`weight`,`sel_msg_num`,`state`,`gas_over_estimation`,`max_fee`,`gas_fee_cap`,`gas_over_premium`,`is_deleted`,`created_at`,`updated_at`\\) VALUES \\(\\?,\\?,\\?,\\?,\\?,\\?,\\?,\\?,\\?,\\?,\\?,\\?,\\?\\)'\n  - is with arguments:\n    0 - d2e4c7dd-54db-41da-9167-5979381d8060\n    1 - t02457644170698675106\n    2 - 986\n    3 - 986\n    4 - 986\n    5 - unknow state 0\n    6 - 986\n    7 - +986\n    8 - +986\n    9 - 986\n    10 - -1\n    11 - {}\n    12 - {}\n  - should return Result having:\n      LastInsertId: 1\n      RowsAffected: 1", err:(*errors.errorString)(0xc0003a6dc0)}
            	Test:       	TestAddress/mysql_test_save_address
    --- FAIL: TestAddress/mysql_test_get_address (0.00s)
        address_test.go:82: 
            	Error Trace:	address_test.go:82
            	            				testing.go:32
            	Error:      	Received unexpected error:
            	            	call to Query 'SELECT * FROM `addresses` WHERE addr = ? and is_deleted = ? LIMIT 1' with args [{Name: Ordinal:1 Value:t2b3ptsj3zw3elh6jsjxrhw4axmlay5dt36perpmq} {Name: Ordinal:2 Value:-1}], was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
            	            	  - matches sql: 'INSERT INTO `addresses` \(`id`,`addr`,`nonce`,`weight`,`sel_msg_num`,`state`,`gas_over_estimation`,`max_fee`,`gas_fee_cap`,`gas_over_premium`,`is_deleted`,`created_at`,`updated_at`\) VALUES \(\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?,\?\)'
            	            	  - is with arguments:
            	            	    0 - d2e4c7dd-54db-41da-9167-5979381d8060
            	            	    1 - t02457644170698675106
            	            	    2 - 986
            	            	    3 - 986
            	            	    4 - 986
            	            	    5 - unknow state 0
            	            	    6 - 986
            	            	    7 - +986
            	            	    8 - +986
            	            	    9 - 986
            	            	    10 - -1
            	            	    11 - {}
            	            	    12 - {}
            	            	  - should return Result having:
            	            	      LastInsertId: 1
            	            	      RowsAffected: 1
            	Test:       	TestAddress/mysql_test_get_address
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x141c2eb]

goroutine 50 [running]:
testing.tRunner.func1.2({0x2154760, 0x34afdd0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1212 +0x3b6
panic({0x2154760, 0x34afdd0})
	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1047 +0x266
github.com/filecoin-project/venus-messager/models/mysql.testGetAddress(0x63032f0d, {0x28ee4a8, 0xc00033aed0}, {0x28ffdc0, 0xc0009e9a40})
	/home/runner/work/venus-messager/venus-messager/models/mysql/address_test.go:83 +0x4cb
github.com/filecoin-project/venus-messager/models/mysql.wrapper.func1(0x0)
	/home/runner/work/venus-messager/venus-messager/models/mysql/testing.go:32 +0x8c
testing.tRunner(0xc000474340, 0xc000afc360)
	/opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1306 +0x727
FAIL	github.com/filecoin-project/venus-messager/models/mysql	0.207s
```

**Comment by simlecode** [comment]
已修复，原因是使用gorm create 数据时，如果该字段是 0 值，则会使用默认的值，修复代码：https://github.com/filecoin-project/venus-messager/blob/master/models/mysql/address_test.go#L287
