### ISSUE TITLE
[venus-miner] 在计算所有节点赢票时，进程panic退出

### ISSUE THREAD

**Issue by cloudxin** [filecoin-project/venus#5419]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 版本 / Version

```text
venus-miner -v
venus-miner version 1.6.0'+git4dfe5c3'
```

### 描述 / Describe the Bug

master分支上的venus-miner在计算所有节点赢票数时，出现了进程panic后异常退出

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/43364105/197924604-91b28d7c-352b-4ee7-9a53-5edd91a1a524.png">

### 日志 / Logging Information

```text
2022-10-26T10:48:51.098+0800    ERROR   rpc     go-jsonrpc@v0.1.4-0.20210721095535-a67dff16de21/websocket.go:498        sending ping message: write tcp 172.16.1.52:58350->172.16.1.51:45132: write: broken pipe
2022-10-26T10:48:51.098+0800    ERROR   rpc     go-jsonrpc@v0.1.4-0.20210721095535-a67dff16de21/websocket.go:498        sending ping message: write tcp 172.16.1.52:58306->172.16.1.51:45132: write: broken pipe
2022-10-26T10:48:52.207+0800    INFO    miner   miner/miningmgr.go:135  count winners, addrs: [], start: 2280000, end: 2281535
panic: close of closed channel

goroutine 3281024 [running]:
github.com/filecoin-project/go-jsonrpc.websocketClient.func3()
        /root/go/pkg/mod/github.com/ipfs-force-community/go-jsonrpc@v0.1.4-0.20210721095535-a67dff16de21/client.go:283 +0x26
github.com/filecoin-project/venus-miner/miner.NewMiner.func2.1({0x17ca1c0?, 0xc0036b6a20?}, {0xc000f18580?, 0xc003d05d88?}, {{0xc01bfd8c00?, 0xc01bfe43f0?}}, {0xc00182a990?, 0x88?, 0x497a55494a694f01?}, {{0x1411829, ...}, ...})
        /opt/venus-miner/miner/multiminer.go:116 +0x10f
github.com/filecoin-project/venus-miner/miner.ComputeVRF({0x17ca1c0?, 0xc0036b6a20?}, 0xc0036b6a20?, {0xc000f18580?, 0x0?}, {{0xc01bfd8c00?, 0xc0048f8000?}}, {0xc00182a990, 0x88, 0x88})
        /opt/venus-miner/miner/util.go:26 +0x88
github.com/filecoin-project/venus-miner/miner.IsRoundWinner({0x17ca1c0, 0xc0036b6a20}, 0x22ca55, {0xc000f18580, 0x9}, {{0xc001206270, 0x4}}, {0x2440ba, {0xc01bfe84e0, 0x60, ...}}, ...)
        /opt/venus-miner/miner/util.go:62 +0x2ea
github.com/filecoin-project/venus-miner/miner.(*Miner).winCountInRound(0xc000f32000, {0x17ca1c0, 0xc0036b6a20}, {0xc000f18580, 0x9}, {{0xc001206270?, 0x0?}}, 0x0?, 0x0?)
        /opt/venus-miner/miner/miningmgr.go:131 +0x1f8
github.com/filecoin-project/venus-miner/miner.(*Miner).CountWinners.func1.1(0x22ca54)
        /opt/venus-miner/miner/miningmgr.go:199 +0xea
created by github.com/filecoin-project/venus-miner/miner.(*Miner).CountWinners.func1
        /opt/venus-miner/miner/miningmgr.go:196 +0x606
panic: close of closed channel

goroutine 3281019 [running]:
github.com/filecoin-project/go-jsonrpc.websocketClient.func3()
        /root/go/pkg/mod/github.com/ipfs-force-community/go-jsonrpc@v0.1.4-0.20210721095535-a67dff16de21/client.go:283 +0x26
github.com/filecoin-project/venus-miner/miner.NewMiner.func2.1({0x17ca1c0?, 0xc0036b6a20?}, {0xc000f18580?, 0xc003debd88?}, {{0xc01c296400?, 0xc01c2892c0?}}, {0xc0001be7e0?, 0x88?, 0xc003e44f01?}, {{0x1411829, ...}, ...})
        /opt/venus-miner/miner/multiminer.go:116 +0x10f
github.com/filecoin-project/venus-miner/miner.ComputeVRF({0x17ca1c0?, 0xc0036b6a20?}, 0xc0036b6a20?, {0xc000f18580?, 0x0?}, {{0xc01c296400?, 0xc002f60c30?}}, {0xc0001be7e0, 0x88, 0x88})
        /opt/venus-miner/miner/util.go:26 +0x88
github.com/filecoin-project/venus-miner/miner.IsRoundWinner({0x17ca1c0, 0xc0036b6a20}, 0x22ca50, {0xc000f18580, 0x9}, {{0xc001206270, 0x4}}, {0x2440b5, {0xc01c2929c0, 0x60, ...}}, ...)
        /opt/venus-miner/miner/util.go:62 +0x2ea
github.com/filecoin-project/venus-miner/miner.(*Miner).winCountInRound(0xc000f32000, {0x17ca1c0, 0xc0036b6a20}, {0xc000f18580, 0x9}, {{0xc001206270?, 0xc0039217d0?}}, 0x6d5bae?, 0xc0039217b0?)
        /opt/venus-miner/miner/miningmgr.go:131 +0x1f8
github.com/filecoin-project/venus-miner/miner.(*Miner).CountWinners.func1.1(0x22ca4f)
        /opt/venus-miner/miner/miningmgr.go:199 +0xea
created by github.com/filecoin-project/venus-miner/miner.(*Miner).CountWinners.func1
        /opt/venus-miner/miner/miningmgr.go:196 +0x606
panic: close of closed channel
```

**Comment by cloudxin** [comment]
计算命令为
venus-miner winner count --epoch-start 2280000 --epoch-end 2281535
