### ISSUE TITLE
[venus] venus panic for topice exist / venus崩溃， topic exit

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5575]
### 链服务模块 / Chain Service Components

- [X] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

venus启动，同步一会儿后报错
```
2022-12-15T07:32:48.924Z	WARN	chain.store	runtime/panic.go:838	reorgWorker quit
panic: topic already exists

goroutine 178 [running]:
github.com/filecoin-project/venus/app/submodule/mpool.(*MessagePoolSubmodule).Start.func1()
	/root/venus/app/submodule/mpool/mpool_submodule.go:188 +0x145
github.com/filecoin-project/venus/app/submodule/mpool.(*MessagePoolSubmodule).waitForSync.func1({0x0?, 0x0?, 0x0?}, {0xc0425ecf40?, 0x8?, 0x1?})
	/root/venus/app/submodule/mpool/mpool_submodule.go:230 +0x145
github.com/filecoin-project/venus/pkg/chain.(*Store).reorgWorker.func2()
	/root/venus/pkg/chain/store.go:589 +0x363
created by github.com/filecoin-project/venus/pkg/chain.(*Store).reorgWorker
	/root/venus/pkg/chain/store.go:579 +0x17c
```

**Comment by hunjixin** [comment]
启动时， 在启动后同步很快的情况下，有一定概率会出现message topic重复注册的情况， 复现比较困难， 重复启动停止没问题即可。
